import { randomUUID } from "node:crypto";
import type { ComputerTaskAdapter, ComputerTaskRequest, ComputerTaskResult } from "./types.js";

export class MockComputerTaskAdapter implements ComputerTaskAdapter {
  readonly provider = "mock" as const;

  async run(request: ComputerTaskRequest): Promise<ComputerTaskResult> {
    const name = inferFileName(request.instruction);
    return {
      taskId: `mock-${randomUUID()}`,
      status: "waiting_for_approval",
      summary: `Found a likely match on ${request.computerId}.`,
      candidates: [{ name, meta: "Local mock result", ext: extension(name), evidence: "Generated by the local development adapter." }],
      approval: { summary: "Kylian is ready to deliver the selected file.", fileName: name },
    };
  }

  async steer(): Promise<void> {}
  async pause(): Promise<void> {}
  async stop(): Promise<void> {}
}

function inferFileName(instruction: string): string {
  const match = instruction.match(/[\w-]+\.(?:pdf|pptx|docx|xlsx|png|jpg)/i);
  return match?.[0] ?? "matching-file.pdf";
}

function extension(name: string): string {
  return name.split(".").pop()?.toUpperCase() ?? "FILE";
}
